version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8  # Python environment
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout  # Check out the repository code
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget xvfb chromium-browser
            pip install selenium
      - run:
          name: Run the test with screen recording
          command: |
            Xvfb :99 -screen 0 1280x1024x16 & # Start virtual display
            export DISPLAY=:99
            wget https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/
            python test_script.py
            # Optionally record the session
            ffmpeg -video_size 1280x1024 -framerate 25 -f x11grab -i :99.0 screen_recording.mp4

workflows:
  version: 2
  scheduled_tests:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * *"  # Runs daily at midnight
          filters:
            branches:
              only:
                - circleci-project-setup  # Replace 'main' with your branch name if different
