version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable xvfb
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            pip install selenium
      - run:
          name: Run the test with screen recording
          command: |
            Xvfb :99 -screen 0 1280x1024x16 & # Start virtual display
            export DISPLAY=:99
            google-chrome --version  # Verify Chrome is installed
            python test_script.py
            # Optionally record the session
            ffmpeg -video_size 1280x1024 -framerate 25 -f x11grab -i :99.0 screen_recording.mp4

release:
  executor: python-executor
  steps:
    - checkout
    - run: echo "Replace this with your release steps"

workflows:
  hourly-tests:
    jobs:
      - test

  build-and-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/  # Ignore all branches
            tags:
              only: /^v.*/  # Only trigger on tags that start with 'v'
