version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Chromium Browser
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser xvfb
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            pip install selenium
      - run:
          name: Run the test with screen recording
          command: |
            Xvfb :99 -screen 0 1280x1024x16 & # Start virtual display
            export DISPLAY=:99
            chromium-browser --version  # Check Chromium installation
            python test_script.py
            # Optionally record the session
            ffmpeg -video_size 1280x1024 -framerate 25 -f x11grab -i :99.0 screen_recording.mp4

release:
  executor: python-executor
  steps:
    - checkout
    - run: echo "Replace this with your release steps"

workflows:
  hourly-tests:
    jobs:
      - test

  build-and-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/  # Ignore all branches
            tags:
              only: /^v.*/  # Only trigger on tags that start with 'v'
