version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Download Chromium Browser
          command: |
            wget https://chromium-browser-snapshots.appspot.com/downloads/latest/chromium-browser-latest-linux64.zip
            unzip chromium-browser-latest-linux64.zip
            mv chromium-browser-latest-linux64/chromium /usr/local/bin/chromium
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget xvfb
            pip install selenium
      - run:
          name: Run the test with screen recording
          command: |
            Xvfb :99 -screen 0 1280x1024x16 & # Start virtual display
            export DISPLAY=:99
            python test_script.py
            # Optionally record the session
            ffmpeg -video_size 1280x1024 -framerate 25 -f x11grab -i :99.0 screen_recording.mp4

# This job is just an example and can be replaced with your actual release job
release:
  executor: python-executor
  steps:
    - checkout
    - run: echo "Replace this with your release steps"

workflows:
  # Hourly workflow using environment variable
  hourly-tests:
    jobs:
      - test

# Original workflow (unchanged)
  build-and-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/  # Ignore all branches
            tags:
              only: /^v.*/  # Only trigger on tags that start with 'v'#
